### ISSUE TITLE
Publish on Packagist

### ISSUE THREAD

**Issue by mzur** [jevets/kirby-form#5]
Please publish this repo on Packagist so no extra `repositories` URL is required in the `composer.json`.

**Comment by mzur** [comment]
I've now established my [fork](https://github.com/mzur/kirby-form) and published it on Packagist so it can be used with Uniform. Once you've got more time for this we can work on merging the fork back into your repo :wink:

**Comment by jevets** [comment]
Sorry Martin, I've been too busy with client work. I'm glad you forked and published it. 

One day I'll probably get back around to this project, but probably not until I have another client project that needs Kirby.

**Comment by jevets** [comment]
@mzur 

I posted a note on the repo's README that I don't maintain it anymore, pointing over to your repo instead. Hope you don't mind :)

**Comment by mzur** [comment]
Not at all, good idea :wink:
